---
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: Upgrade all apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Update raspi-config itself
  become: true
  apt: name=raspi-config update_cache=yes state=present cache_valid_time=3600
