---

- name: Disable WiFi
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE WIFI"
    block: |
      dtoverlay=pi3-disable-wifi
  when: WIFI == False

- name: Enable WiFi
  blockinfile:
    path: /boot/config.txt
    marker: "# {mark} ANSIBLE DISABLE WIFI"
    block: |
      dtoverlay=pi3-disable-wifi
    state: absent
  when: WIFI == True


