---

#- name: rm kubeconfig2
#  shell: "rm kubeconfig2"
#  delegate_to: 127.0.0.1

- name: setup kubeconfig
  shell: "k3sup install --skip-install --ip {{ leader_ip }} --user pi --local-path $HOME/.kube/config --context k3s"
  delegate_to: 127.0.0.1
#  when: (not (k3s.stat.exists)) or (k3s.stat.exists and force == True)
